config/routes.rb
TamilCorpus::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :tags

  resources :words do
    collection do
      get 'import'
      post 'file_processor'
      get 'tagged'
      get 'untagged'
      get 'locked'
      get 'file_upload'
      post 'file_process'
    end
    
    member do
      post "tag"
      post "untag"
      get "refresh_tags"
      get "refresh_untags"
      get "lock_it"
      get "unlock_it"
    end
  end

  get "corpus/index"

  root :to => 'corpus#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :tags
  
  ##
  # Tags that are not associated with this word
  def untags
    Tag.all.order(:name) - tags
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :tagged, :untagged, :locked] 
  before_filter :user_must_be_admin, only: [:new, :edit, :create, :update, :destoy, :lock_it, :unlock_it]
  
  # GET /words
  # GET /words.json
  def index
    @words = Word.all
    @heeading = "All Words"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])
    @tags = @word.tags.order(:name)
    @untags = Tag.order(:name) - @tags
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
  
  def tagged
    @words = Word.where(tagged: true)
    @heading = "Tagged Words" 
    render :index 
  end
  
  def untagged
    @words = Word.where(tagged: false)
    @heading = "Untagged Words"
    render :index
  end
  
  def locked
    @words = Word.where(locked: true)
    @heading = "Locked Words"
    render :index
  end
  
  def tag
    tag = Tag.find(params[:tag_id])
    word = Word.find(params[:id])
    word.tags << tag
    word.tagged = true
    word.save
    # @untags = Tag.order(:name) - word.tags
    respond_to do |format|
      format.js{}
    end
  end
  
  def untag
    tag = Tag.find(params[:tag_id])
    word = Word.find(params[:id])
    word.tags.delete tag
    word.tagged = false if word.tags.count == 0 
    word.save
    # @tags = word.tags
    respond_to do |format|
      format.js{}
    end
  end
  
  def refresh_tags
    @tags = Word.find(params[:id]).tags.order(:name)
    render layout: false
  end
  
  def refresh_untags
    @untags = Tag.order(:name) - Word.find(params[:id]).tags
    render layout: false
  end
  
  def lock_it
    word = Word.find(params[:id])
    word.locked = true
    word.save
    redirect_to word, notice: "Word has been locked"
  end
  
  def unlock_it
    word = Word.find(params[:id])
    word.locked = false
    word.save
    redirect_to word, notice: "Word has ben unlocked"
  end
  
  def file_upload
  end
  
  def file_process
    file = params[:file].read
    words = file.split /,/
    for word in words
      Word.find_or_create_by_name word.strip
    end
    redirect_to :words_path, notice: "Hopefully file has been processed right"
  end
  
  private
  
  def user_must_be_admin
    redirect_to words_path, notice: "You must be admin to perform this task" unless current_user.admin?
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_added_tag.html.haml
%li
  = check_box_tag "tag", 1, true, id: added_tag.id
  = added_tag.name

app/views/words/_form.html.haml
= form_for @word do |f|
  - if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/words/_tags.html.haml
%p Tags
%ul= render partial: 'added_tag', collection: @tags

:javascript
  $('#tags .tags :checkbox').click(function() {
      var $this = $(this);
      // $this will contain a reference to the checkbox   
      if ($this.is(':checked')) {
          // the checkbox was checked 
          
      } else {
          // the checkbox was unchecked
          var tag_id = $this.attr('id').match(/\d+/g);
          $.post("/words/"+word_id+"/untag",
          {
            tag_id: tag_id
          });
          $('#tags .untags').load("/words/"+word_id+"/refresh_untags");
          $this.parent().remove();
      }
  });

app/views/words/_untags.html.haml
%p Untags
%ul= render @untags

:javascript
  $('#tags .untags :checkbox').click(function() {
      var $this = $(this);
      // $this will contain a reference to the checkbox   
      if ($this.is(':checked')) {
          // the checkbox was checked 
          var tag_id = $this.attr('id').match(/\d+/g);
          $.post("/words/"+word_id+"/tag",
          {
            tag_id: tag_id
          });
          $('#tags .tags').load("/words/"+word_id+"/refresh_tags");
          $this.parent().remove();
      } else {
          // the checkbox was unchecked
      }
  });

app/views/words/_word.html.haml
= link_to word.name, word
- if user_signed_in? and current_user.admin?
  = link_to raw('<i class="icon-pencil"></i>'), edit_word_path(word)
  = link_to raw('<i class="icon-trash"></i>'), word, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/words/_word_id.html.erb
<script type="text/javascript">
  var word_id = <%= @word.id %>;
</script>

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', @word
\|
= link_to 'Back', words_path

app/views/words/file_upload.html.haml
= form_tag({action: :file_process}, multipart: true) do
  = file_field_tag :file
  = submit_tag "Upload CSV"
 

app/views/words/import.html.haml
= form_tag({action: :file_processor}, multipart: true) do
  = file_field_tag :file
  = submit_tag "Upload"

app/views/words/index.html.haml
%h1= @heading
%p= link_to 'புதிய வார்த்தை', new_word_path, class: "btn btn-primary"
#word_list= render @words

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', words_path

app/views/words/refresh_tags.html.haml
%p Tags
%ul= render partial: 'added_tag', collection: @tags

:javascript
  $('#tags .tags :checkbox').click(function() {
      var $this = $(this);
      // $this will contain a reference to the checkbox   
      if ($this.is(':checked')) {
          // the checkbox was checked 
          
      } else {
          // the checkbox was unchecked
          var tag_id = $this.attr('id').match(/\d+/g);
          $.post("/words/"+word_id+"/untag",
          {
            tag_id: tag_id
          });
          $('#tags .untags').load("/words/"+word_id+"/refresh_untags");
          $this.parent().remove();
      }
  });

app/views/words/refresh_untags.html.haml
%p Untags
%ul= render @untags

:javascript
  $('#tags .untags :checkbox').click(function() {
      var $this = $(this);
      // $this will contain a reference to the checkbox   
      if ($this.is(':checked')) {
          // the checkbox was checked 
          var tag_id = $this.attr('id').match(/\d+/g);
          $.post("/words/"+word_id+"/tag",
          {
            tag_id: tag_id
          });
          $('#tags .tags').load("/words/"+word_id+"/refresh_tags");
          $this.parent().remove();
      } else {
          // the checkbox was unchecked
      }
  });

app/views/words/show.html.haml
%p#notice= notice

%h1= @word.name
%p.wod-actions
  = link_to "Edit", edit_word_path(@word), class: "btn btn-primary"
  = link_to "Delete", @word, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-primary"
  = link_to "Lock It", lock_it_word_path(@word), class: "btn btn-primary" unless @word.locked
  = link_to "Unlock It", unlock_it_word_path(@word), class: "btn btn-primary" if @word.locked

#tags
  = render partial: 'word_id'
  .row-fluid
    .span6
      .tags= render partial: 'tags'
    .span6
      .untags= render partial: 'untags'