config/routes.rb
TamilCorpus::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :tags

  resources :words do
    collection do
      get 'import'
      post 'file_processor'
      get 'tagged'
      get 'untagged'
      get 'locked'
      get 'file_upload'
      post 'file_process'
    end
    
    member do
      post "tag"
      post "untag"
      get "refresh_tags"
      get "refresh_untags"
      get "lock_it"
      get "unlock_it"
    end
  end

  get "corpus/index"

  root :to => 'corpus#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TamilCorpus"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") சொற்கண்டு
          .container.nav-collapse
            %ul.nav
              %li= link_to "வார்த்தைகள்", words_path
              %li= link_to "தொகுத்தவை", untagged_words_path
              %li= link_to "தொகுக்காதவை", tagged_words_path
              %li= link_to "உறுதி செய்யப்பட்டவை", locked_words_path
            .pull-right
              -if user_signed_in?
                = link_to "Logout", destroy_user_session_path, class: "btn", method: :delete
              -else
                = link_to "Login", new_user_session_path, class: "btn"  

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "சொற்கண்டு முயற்சி", "/path1"
              %li= link_to "பங்களியுங்கள்", "/path2"
              %li= link_to "உதவி", "/path3"
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2013
   